# Сеть
bind 0.0.0.0
port 6379
protected-mode yes

# Память
# лимит RAM
maxmemory 2048mb 
# вытеснение по LRU
maxmemory-policy allkeys-lru
# активация дефрагментации
activedefrag yes

# Живучесть (Для очередей и кэша)
# включает AOF
appendonly no

# Производительность
# добавляем потоки для обслуживания запросов (сеть)
io-threads 2
# позволяет потокам парсить входящие запросы
io-threads-do-reads yes 

# отключает RDB полностью (если надо)
save ""
# уменьшаем keepalive
tcp-keepalive 60

# Логи
loglevel notice